name: 🚀 Feature request
title: '🚀 - '
description: Предложить функционал который улучшит проект.
labels: [pending triage]

body:
  - type: textarea
    id: feature-description
    attributes:
      label: Описание
      description: Простыми и понятными словами опишите то что будет полезно для проекта, включая возможные кейсы использования. Если вы работаете либо же имеете готовое решение, пожалуйста оставьте ссылку.
      placeholder: Как-то сидел..

  - type: checkboxes
    id: additional-info
    attributes:
      label: Дополнительная информация
      description: Дополнительная информация внесёт больше ясностей.
      options:
        - label: Я сам добавлю фичу
        - label: Только сообщаю
