name: 🎯 New task
title: '🎯 - '
description: Добавление новой задачи.
labels: [pending triage]

body:
  - type: textarea
    id: bug-description
    attributes:
      label: Описание
      description: Простыми и понятными словами опишите задачу, максимально подробно старайтесь добавить описание которое будет понятно всем.
      placeholder: Как то пришло оповещение об..
